# This is the config file for building TileStache and running the test suite
# with Travis-ci.org

language: python

dist: trusty
sudo: false

python:
  - "2.7"

addons:
  postgresql: "9.4"
  apt:
    packages:
      - proj
      - python-werkzeug

virtualenv:
  system_site_packages: true

services:
  - memcached
  - postgresql

before_install:
  - (cd ~ && wget http://download.osgeo.org/gdal/2.1.1/gdal-2.1.1.tar.gz -O gdal.tar.gz && tar xzf gdal.tar.gz && cd gdal-2.1.1 && ./configure --with-python && make && make install && ldconfig)

install:
  - pip install nose coverage
  - pip install -r requirements.txt

before_script:
  - psql -U postgres -c "drop database if exists test_tilestache"
  - psql -U postgres -c "create database test_tilestache"
  - psql -U postgres -c "create extension postgis" -d test_tilestache
  - ogr2ogr -nlt MULTIPOLYGON -f "PostgreSQL" PG:"user=postgres dbname=test_tilestache" ./examples/sample_data/world_merc.shp

script:
  - nosetests -v --with-coverage --cover-package TileStache

notifications:
  email:
    recipients:
      - mike-travisci@teczno.com
